### ISSUE TITLE
Error yarn start

### ISSUE THREAD

**Issue by yoshixile** [yuyake0084/react-webrtc-starter#1]
Error Info

------------------------------------------------------
[root@tk2-208-13844 react-webrtc-starter]# nvm use v12.14.0
Now using node v12.14.0 (npm v6.13.4)
[root@tk2-208-13844 react-webrtc-starter]# yarn start
yarn run v1.22.11
$ node --max_old_space_size=2048 --gc_interval=100 node_modules/nodemon/bin/nodemon.js
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module '/home/coronuser/react-webrtc-starter/node_modules/nodemon/bin/nodemon.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at internal/main/run_main_module.js:17:11 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[root@tk2-208-13844 react-webrtc-starter]#

**Comment by yuyake0084** [comment]
@yoshixile 
Issueの提起ありがとうございます！
本エラーが発生した環境についていくつか確認したいことがありまして、以下お手すきでご確認お願い致します。

1. 本リポジトリをホスティングさせているサーバー
2. 本エラーが発生するまでに実行したコマンドヒストリー
